#include <cstdlib>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <tesseract/baseapi.h>
#include <tesseract/resultiterator.h>
#include <vector>

int main(int argc, char **argv) {
  tesseract::TessBaseAPI api;
  const char *language = std::getenv("SPECTACLE_OCR_TEST_LANGUAGE");
  if (api.Init(nullptr, language ? language : "chi_sim") != 0)
    return 1;
  api.SetPageSegMode(tesseract::PSM_AUTO);
  // A padded RGB buffer catches accidental inclusion of QImage row padding.
  int width = 33, height = 32, stride = 100;
  std::vector<unsigned char> pixels(height * stride, 255);
  for (int row = 0; row < height; ++row)
    pixels[row * stride + 99] = 17;
  if (argc > 2) {
    // Test-only P6 fixture input (no comments), generated by Pillow.
    std::ifstream file(argv[2], std::ios::binary);
    std::string magic;
    int maximum = 0;
    file >> magic >> width >> height >> maximum;
    if (!file || magic != "P6" || maximum != 255 || width <= 0 || height <= 0 ||
        static_cast<long long>(width) * height * 3 > 64 * 1024 * 1024)
      return 4;
    file.get();
    stride = width * 3;
    pixels.resize(static_cast<size_t>(height) * stride);
    file.read(reinterpret_cast<char *>(pixels.data()), pixels.size());
    if (!file)
      return 4;
  }
  const std::string expected = argc > 1 ? argv[1] : "";
  for (int repeat = 0; repeat < 5; ++repeat) {
    api.SetImage(pixels.data(), width, height, 3, stride);
    if (api.Recognize(nullptr) != 0)
      return 2;
    // Match OcrWorker's virtual TEXTLINE calls and deletion behavior.
    for (int pass = 0; pass < 2; ++pass) {
      std::unique_ptr<tesseract::ResultIterator> iterator(api.GetIterator());
      std::string result;
      if (iterator) {
        do {
          char *text = iterator->GetUTF8Text(tesseract::RIL_TEXTLINE);
          if (text && *text) {
            if (!result.empty())
              result += '\n';
            result += text;
          }
          // Test both documented Tesseract and Spectacle deletion.
          if (pass == 0 && !std::getenv("SPECTACLE_OCR_TEST_DOCUMENTED_DELETE"))
            delete text;
          else
            delete[] text;
        } while (iterator->Next(tesseract::RIL_TEXTLINE));
      }
      if (result != expected) {
        std::cerr << "unexpected OCR result: [" << result << "]\n";
        return 3;
      }
    }
    api.Clear();
  }
  api.End();
  std::cout << "PASS: repeated image/recognize/iterator/clear/end\n";
}
